---
- name: create build directory
  file:
    path: /var/tmp/linux_tweet_app
    state: directory
    owner: rikichrisoliva
    group: rikichrisoliva
    mode: '0755'
- name: copy Dockerfile
  copy:
    src: Dockerfile
    dest: /var/tmp/linux_tweet_app/Dockerfile
    owner: rikichrisoliva
    group: rikichrisoliva
    mode: '0644'
- name: copy linux.png
  copy:
    src: linux.png
    dest: /var/tmp/linux_tweet_app/linux.png
    owner: rikichrisoliva
    group: rikichrisoliva
    mode: '0644'
- name: copy index.html
  copy:
    src: index.html
    dest: /var/tmp/linux_tweet_app/index.html
    owner: rikichrisoliva
    group: rikichrisoliva
    mode: '0644'
- name: build container image
  docker_image:
    name: linux_tweet_app
    source: build
    build:
      path: /var/tmp/linux_tweet_app
    state: present
